name: "Digital Alchemy"
description: "Digital Alchemy code deployment runner"
version: "24.7.2"
slug: "digital_alchemy"
url: https://github.com/Digital-Alchemy-TS/addons/tree/main/digital_alchemy
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  app_root: /share/digital_alchemy
  main: src/main.js
  node_env: production

schema:
  app_root: str
  main: str
  node_env: str

map:
  - share:rw
  - backup:rw
  - config:rw

ports:
  3000/tcp: 3000
