name: "Code Runner"
description: "Digital Alchemy code deployment runner"
version: "24.10.1"
slug: "code_runner"
url: https://github.com/Digital-Alchemy-TS/addons/tree/main/code_runner
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  app_root: /share/digital_alchemy
  node_env: production
  environment: node_npm
  packages: []

schema:
  app_root: str
  node_env: str
  environment: list(node_npm|node_yarn|bun|deno)
  packages:
    - str

map:
  - share:rw
  - backup:rw
  - config:rw

ports:
  3000/tcp: 3000
