name: "Code Runner"
description: "Digital Alchemy code deployment runner"
version: "24.9.1"
slug: "code_runner"
url: https://github.com/Digital-Alchemy-TS/addons/tree/main/code_runner
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  app_root: /share/digital_alchemy
  main: src/main.ts
  node_env: production
  run_mode: tsx
  packages: []

schema:
  app_root: str
  main: str
  node_env: str
  run_mode: list(node|tsx)
  packages:
    - str

map:
  - share:rw
  - backup:rw
  - config:rw

ports:
  3000/tcp: 3000
